In [6]:
import numpy as np

In [ ]:
# LIST vs ARRAY

In [2]:
L=[1,2,3]
A=np.array([1,2,3])

In [5]:
print ("Boucle List")
for e in L:
    print (e)

print ("Boucle Array")
for e in A :
    print (e)

Boucle List
1
2
3
Boucle Array
1
2
3


In [6]:
print ("Append new element only in list")
L.append(4)
L += [5]

Append new element only in list


In [9]:
L2=[]
for e in L:
    L2.append(e+e)
print(L2)

print (A*2)
print (A+A)
print (A**2)
print (np.sqrt(A))

[2, 4, 6, 8, 10]
[2 4 6]
[2 4 6]
[1 4 9]
[1.         1.41421356 1.73205081]


In [11]:
a = np.array([1,2])
b = np.array([2,1])

dot = 0

for e, f in zip(a,b):
    dot += e*f
print(dot)

print(np.sum(a*b))
print(a.dot(b))

4
4
4


In [ ]:
# Matrices

In [10]:
M1 = np.array([[1,2,5],[3,4,6]])
print(M1)
print(M1.mean())
print(M1.var())

[[1 2 5]
 [3 4 6]]
3.5
2.9166666666666665


In [11]:
O = np.zeros((10,10))
print (O)

R = np.random.random((3,2))
print(R)

M2 = np.array([[5,6,15],[2,15,14],[0,4,8]])
M1.dot(M2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.96223837 0.63498936]
 [0.89179935 0.99853948]
 [0.97279196 0.1673199 ]]


array([[  9,  56,  83],
       [ 23, 102, 149]])

In [13]:
# Solving linear system
# Ax=b
# A is a matrix of parameters, b a vector and we want to find a vector x
# Manual solution : invert(A)b=x
A = np.array([[1,1], [1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(A,b)
print(x)



[1500.  700.]
