In [1]:
import numpy as np

In [2]:
L=[1,2,3]
A=np.array([1,2,3])

In [5]:
print ("Boucle List")
for e in L:
    print (e)

print ("Boucle Array")
for e in A :
    print (e)

Boucle List
1
2
3
Boucle Array
1
2
3


In [6]:
print ("Append new element only in list")
L.append(4)
L += [5]

Append new element only in list


In [9]:
L2=[]
for e in L:
    L2.append(e+e)
print(L2)

print (A*2)
print (A+A)
print (A**2)
print (np.sqrt(A))

[2, 4, 6, 8, 10]
[2 4 6]
[2 4 6]
[1 4 9]
[1.         1.41421356 1.73205081]


In [11]:
a = np.array([1,2])
b = np.array([2,1])

dot = 0

for e, f in zip(a,b):
    dot += e*f
print(dot)

print(np.sum(a*b))
print(a.dot(b))

4
4
4
